//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fabrics.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderProduct = new HashSet<OrderProduct>();
        }
    
        public int ID_Product { get; set; }
        public string Articul { get; set; }
        public string Name { get; set; }
        public string DescriptionProduct { get; set; }
        public int ID_Category { get; set; }
        public string Photo { get; set; }
        public int ID_Manufacture { get; set; }
        public string Cost { get; set; }
        public int CurrentDiscount { get; set; }
        public int MaxDiscount { get; set; }
        public int QuantityStock { get; set; }
        public int ID_UnitMeasurement { get; set; }
        public int ID_Supplier { get; set; }
    
        public virtual CategoryProduct CategoryProduct { get; set; }
        public virtual ManufactureProduct ManufactureProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderProduct> OrderProduct { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual UnitMeasurement UnitMeasurement { get; set; }
    }
}
